---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-circuit-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wiki-circuit-server
  template:
    metadata:
      labels:
        app: wiki-circuit-server
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: wiki-circuit-server
        image: linkedmink/wiki-circuit-server
        ports:
        - containerPort: 8080
        env:
        - name: ALLOWED_ORIGINS
          value: '["https://wiki-circuit.linkedmink.space","http://wiki-circuit.linkedmink.space"]'
        - name: JOB_MAX_DEPTH
          value: "2"
        - name: JOB_MAX_PARALLEL_DOWNLOADS
          value: "8"
        - name: REDIS_MODE
          value: "Sentinal"
        - name: REDIS_HOSTS
          value: '[{ "host": "my-redis-sentinal.local", "port": 26379 }]'

---
apiVersion: v1
kind: Service
metadata:
  name: wiki-circuit-server
spec:
  ports:
  - port: 8080
  selector:
    app: wiki-circuit-server
