---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-circuit-task-processor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wiki-circuit-task-processor
  template:
    metadata:
      labels:
        app: wiki-circuit-task-processor
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      volumes:
      - name: jwt-public-key
        secret:
          secretName: jwt-public-key
      containers:
      - name: wiki-circuit-task-processor
        image: linkedmink/wiki-circuit-task-processor
        ports:
        - containerPort: 8080
        env:
        - name: JWT_SECRET_KEY_FILE
          value: "jwtRS256.key.pub"
        - name: JWT_AUDIENCE
          value: "client.[Your Domain]"
        - name: JWT_ISSUER
          value: "api.[Your Domain]"
        - name: JOB_MAX_DEPTH
          value: "2"
        - name: JOB_MAX_PARALLEL_DOWNLOADS
          value: "8"
        - name: REDIS_MODE
          value: "Sentinal"
        - name: REDIS_HOSTS
          value: '[{ "host": "my-redis-sentinal.local", "port": 26379 }]'

---
apiVersion: v1
kind: Service
metadata:
  name: wiki-circuit-task-processor
spec:
  ports:
  - port: 8080
  selector:
    app: wiki-circuit-task-processor
